### ISSUE TITLE
Implement character

### ISSUE THREAD

**Issue by lsnellingen** [DeimosA/TDT4240-AstroSplit#3]

**Comment by HenrikMidtun** [comment]
Have made some Components and systems, working on rendering to screen

TODO:
Make all components Poolable 
https://github.com/libgdx/ashley/wiki/Efficient-Entity-Systems-with-pooling#pooled-components

**Comment by lsnellingen** [comment]
Made components poolable on new branch for the issue called character.

**Comment by HenrikMidtun** [comment]
Closing this, breaking down into smaller issues
